Keep the process busy, add while for X Server

diff --git a/utils/xinitrc b/utils/xinitrc
--- a/utils/xinitrc
+++ b/utils/xinitrc
@@ -1,22 +1,37 @@
 #!/bin/sh
 # Origin: http://blogs.wcode.org/2013/09/howto-boot-your-raspberry-pi-into-a-fullscreen-browser-kiosk/
+while true; do
 
-# Generate the bare minimum to keep Chromium happy!
-mkdir -p /home/pi/.config/chromium/Default
-sqlite3 /home/pi/.config/chromium/Default/Web\ Data "CREATE TABLE meta(key LONGVARCHAR NOT NULL UNIQUE PRIMARY KEY, value LONGVARCHAR); INSERT INTO meta VALUES('version','46'); CREATE TABLE keywords (foo INTEGER);";
+	# Clean up previously running apps, gracefully at first then harshly
+	killall -TERM chromium 2>/dev/null;
+	killall -TERM matchbox-window-manager 2>/dev/null;
+	sleep 2;
+	killall -9 chromium 2>/dev/null;
+	killall -9 matchbox-window-manager 2>/dev/null;
 
-# Disable DPMS / Screen blanking
-xset -dpms
-xset s off
+	# Clean out existing profile information
+	rm -rf /home/pi/.cache;
+	rm -rf /home/pi/.config;
+	rm -rf /home/pi/.pki;
 
-# Reset the framebuffer's colour-depth
-fbset -depth $( cat /sys/module/*fb*/parameters/fbdepth );
+	# Generate the bare minimum to keep Chromium happy!
+	mkdir -p /home/pi/.config/chromium/Default
+	sqlite3 /home/pi/.config/chromium/Default/Web\ Data "CREATE TABLE meta(key LONGVARCHAR NOT NULL UNIQUE PRIMARY KEY, value LONGVARCHAR); INSERT INTO meta VALUES('version','46'); CREATE TABLE keywords (foo INTEGER);";
 
-# Hide the cursor (move it to the bottom-right, comment out if you want mouse interaction)
-xwit -root -warp $( cat /sys/module/*fb*/parameters/fbwidth ) $( cat /sys/module/*fb*/parameters/fbheight )
+	# Disable DPMS / Screen blanking
+	xset -dpms
+	xset s off
 
-# Start the window manager (remove "-use_cursor no" if you actually want mouse interaction)
-matchbox-window-manager -use_titlebar no -use_cursor no &
+	# Reset the framebuffer's colour-depth
+	fbset -depth $( cat /sys/module/*fb*/parameters/fbdepth );
 
-# Start the browser (See http://peter.sh/experiments/chromium-command-line-switches/)
-chromium  --app=http://localhost/#dashboard
+	# Hide the cursor (move it to the bottom-right, comment out if you want mouse interaction)
+	xwit -root -warp $( cat /sys/module/*fb*/parameters/fbwidth ) $( cat /sys/module/*fb*/parameters/fbheight )
+
+	# Start the window manager (remove "-use_cursor no" if you actually want mouse interaction)
+	matchbox-window-manager -use_titlebar no -use_cursor no &
+
+  # Start the browser (See http://peter.sh/experiments/chromium-command-line-switches/)
+  chromium  --app=http://localhost/#dashboard
+
+done;
